### PR TITLE
Dash usability

### PR DESCRIPTION
**Pull request by grantrobertsmith**
I added a placeholder to the create-card directive.

### CODE REVIEW

**Comment by grantrobertsmith** [comment]
It's not currently a user facing change in our system as it only affects the dashboard for filter creation. I tested in safari, chrome and ie10.

**Comment by nwhatt** [comment]
You should bump the bower package version here so we can explicitly update it in the main repo.

**Comment by nwhatt** [comment]
Can you add an example to the gh-pages version of this?

**Comment by grantrobertsmith** [comment]
I updated the ghpages and bower version. To test locally in the app, point your local RedoxEngine repo's bower package for rui-components to your local rui-components repo on the pr branch and go to http://localhost:9000/#/dashboard/organization/123/filters/

**Pull request merged**
